version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - cd BackEnd/javaStack
  build:
    commands:
      - mvn clean compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/javaStack-0.0.1-SNAPSHOT.jar
